vacuum:
    platform: xiaomi_miio
    host: !secret vacuum_host
    token: !secret vacuum_token
    
sensor:
 platform: template
 sensors:
      vacuum_status:
        friendly_name: Статус
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
#        value_template: 'Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
        icon_template: >
          {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.status  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
        friendly_name: Всасывание
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
#        value_template: 'Mode: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}'
        icon_template: 'mdi:speedometer'
      vacuum_battery:
        friendly_name: Заряд батареи
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
#        value_template: 'Battery: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
        unit_of_measurement: '%'
        icon_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}'
      vacuum_cleaning_time:
        friendly_name: Последняя уборка
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}'
        icon_template: 'mdi:timer'
      vacuum_cleaned_area:
        friendly_name: Площадь
        unit_of_measurement: 'm ²'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}'
        icon_template: 'mdi:ruler'
      vacuum_cleanmainbrush:
        friendly_name: Ресурс щетки
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
#        value_template: 'Main Brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush:
        friendly_name: Ресурс боковой щетки
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
#        value_template: 'Side brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleanfilter:
        friendly_name: Ресурс фильтра
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
#        value_template: 'Filter: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_sensordirtyleft:
        friendly_name: Ресурс датчиков
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
#        value_template: 'Sensor: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_do_not_disturb:
        friendly_name: Не беспокоить
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb }}'
        icon_template: >
          {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb  %}
          {% if val == 'on' %}
            mdi:do-not-disturb
          {% else %}
            mdi:do-not-disturb-off
          {% endif %}
      vacuum_operation:
        value_template: 'Operation'
      vacuum_accessories:
        value_template: 'Maintenance'

switch:
  - platform: mqtt
    name: "vacuum_schedule"
    command_topic: "home/bedroom/schedule/set"
    state_topic: "home/bedroom/schedule/set"
    retain: "true"

input_select:
  vacuum_room:
    name: Выберите комнату
    options:
      - Select Input
      - Зал
      - Спальня
      - Кухня
      - Коридор
  vacuum_fan_speed_list:
    name: Мощность всасывания
    options:
      - Quiet
      - Balanced
      - Turbo
      - Max

automation:
  - alias: Set Fan Mode
    initial_state: true
    trigger:
      platform: state
      entity_id: input_select.vacuum_fan_speed_list
    action:
    - service: vacuum.set_fan_speed
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        fan_speed: "{{ states('input_select.vacuum_fan_speed_list') }}"

  - alias: Update Input Select Fan Mode
    initial_state: true
    trigger:
    ##TODO
      - platform: state
        entity_id: sensor.vacuum_fan_speed
      - platform: homeassistant
        event: start
    condition:
      condition: template
      value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') != states('input_select.vacuum_fan_speed_list') }}"
    action:
      - service: input_select.select_option
        entity_id: input_select.vacuum_fan_speed_list
        data_template:
          option: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') }}"

  - alias: Start Cleaning Room
    hide_entity: true
    initial_state: true
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room
      from: 'Select Input'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "Зал") %}
            script.vacuum_living_room
          {% elif is_state("input_select.vacuum_room", "Спальня") %}
            script.vacuum_bed_room
          {% elif is_state("input_select.vacuum_room", "Кухня") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Коридор") %}
            script.vacuum_koridor
          {% else %}
          {% endif %}
    - service: vacuum.set_fan_speed
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        fan_speed: Max
    - service: input_select.select_option
      entity_id: input_select.vacuum_room
      data_template:
        option: "Select Input"
        

#-----------------------------------------------------------Робот завершил уборку
  - alias: Робот пылесос закончил уборку
    initial_state: false
    trigger:
    - platform: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      from: 'cleaning'
      to: 'returning'
    action:
     - service: vacuum.set_fan_speed
       data_template:
         entity_id: vacuum.xiaomi_vacuum_cleaner
         fan_speed: Quiet
     - service: notify.android
       data:
         title: Событие дома
         message: Пылесос закончил уборку

  - alias: Робот пылесос ошибка
    initial_state: true
    trigger:
    - platform: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      to: 'error'
    action:
     - service: notify.android
       data:
         title: Событие дома
         message: Робот пылесос ошибка {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.error }} 
         target: Galaxy_S6  
         
# Зал [[24531,25035,29581,29785,1]]
#Спальня [[25120,20953,30470,25053,2]]
# Кухня  [[20755, 26622,23905,31822,2]]
# Коридор [[19282,20911,24532,26611,2]]

script:
  vacuum_living_room:
        alias: "vacuum_living_room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[21884,23526,26184,29376,1]]
          - service: notify.android
            data:
              title: Событие дома
              message: Пылесос приступил к уборке в Зале
  vacuum_bed_room:
        alias: "vacuum_bed_room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[26174,24845,30174,30245,1]]
          - service: notify.android
            data:
              title: Событие дома
              message: Пылесос приступил к уборке в Спальне
  vacuum_kitchen:
        alias: "vacuum_kitchen"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[24575, 18741,30275,24941,1]]
          - service: notify.android
            data:
              title: Событие дома
              message: Пылесос приступил к уборке в Кухне
  vacuum_koridor:
        alias: "vacuum_koridor"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[19282,20911,24532,26611,1]]
          - service: notify.android
            data:
              title: Событие дома
              message: Пылесос приступил к уборке в Коридоре

